=== Werner91/WebProg_v2/catalogs/schema_fragenkatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="fragenkatalog">
	  <xs:complexType>
	    <xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="fragenblock"/>
		</xs:sequence>
	    <xs:attribute name="name" type="xs:string" use="required"/>
	    <xs:attribute name="fragenanzahl" type="xs:string" use="required"/>
	  </xs:complexType>
	</xs:element>
	
	<xs:element name="fragenblock">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="frage"/>
	      <xs:element ref="antwort"/>
	      <xs:element ref="antwort"/>
	      <xs:element ref="antwort"/>
	      <xs:element ref="antwort"/>
	    </xs:sequence>
	      <xs:attribute name="timeout" type="xs:integer" default="10"/>
	  </xs:complexType>
	</xs:element>
	
	<xs:element name="frage">
	  <xs:complexType mixed="true"/> <!-- mixed: Fragen kÃ¶nnen in beliebiger Reihenfolge drankommen? -->
	</xs:element>
	
	<xs:element name="antwort">
	 <xs:complexType mixed="true">
			<xs:attribute name="korrekt" type="xs:string" default="false"/>
     </xs:complexType>
	</xs:element>

</xs:schema>

=== Werner91/WebProg_v2/catalogs/systemprogrammierung.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/xmlstyle.xsl"?>
<fragenkatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema_fragenkatalog.xsd" name="systemprogrammierung" fragenanzahl="12">
	<fragenblock timeout="30" >
		<frage>Ein Thread soll auf ein durch einen anderen Thread ausgelöstes Ereignis warten. Welcher Mechanismus ist geeignet?
		</frage>
		<antwort korrekt="true">nur Semaphore</antwort>
		<antwort korrekt="false">nur Mutex</antwort>
		<antwort korrekt="false">weder Semaphore noch Mutexe</antwort>
		<antwort korrekt="false">sowohl Semaphore als auch Mutexe</antwort>
	</fragenblock>
	<fragenblock timeout="20">
		<frage>Der Systemaufruf fork...</frage>
		<antwort korrekt="true">...erzeugt einen neuen Prozess, der das gleiche Programm ausführt.</antwort>
		<antwort korrekt="false">...erzeugt einen neuen Prozess, der ein anderes Programm ausführt.</antwort>
		<antwort korrekt="false">...erzeugt einen neuen Thread.</antwort>
		<antwort korrekt="false">...ist das logische Gegenstück zum Aufruf knife.</antwort>
	</fragenblock>
	<fragenblock timeout="30">
		<frage>In einem Signalhandler...</frage>
		<antwort korrekt="true">...dürfen nur bestimmte Funktionen aufgerufen werden.</antwort>
		<antwort korrekt="false">...kann man problemlos alles machen, was man auch im regulären Programmcode macht.</antwort>
		<antwort korrekt="false">...dürfen keine Fließkommaoperationen durchgeführt werden.</antwort>
		<antwort korrekt="false">...ist nur der Systemaufruf write verboten.</antwort>
	</fragenblock>
	<fragenblock timeout="30">
		<frage>Sie möchten eine Datenstruktur vor gleichzeitigem Zugriff aus mehreren Threads schützen. Welcher Mechanismus ist dafür geeignet?</frage>
		<antwort korrekt="true">sowohl Semaphore als auch Mutexe</antwort>
		<antwort korrekt="false">nur Semaphore</antwort>
		<antwort korrekt="false">nur Mutexe</antwort>
		<antwort korrekt="false">nur Signale</antwort>
	</fragenblock>
	<fragenblock timeout="30">
		<frage>Es soll darauf gewartet werden, dass Daten eintreffen, allerdings nur eine bestimmte Zeit. Wie kann man das umsetzen?
		</frage>
		<antwort korrekt="true">mit dem Systemaufruf select</antwort>
		<antwort korrekt="false">durch einen zusätzlichen Timeout-Parameter bei read oder recv</antwort>
		<antwort korrekt="false">gar nicht</antwort>
		<antwort korrekt="false">durch Setzen des Timeout-Status mit fcntl</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Mit welchem Systemaufruf kann man den Port festlegen, auf dem ein Serverprogramm auf Verbindungen wartet?
		</frage>
		<antwort korrekt="true">bind</antwort>
		<antwort korrekt="false">accept</antwort>
		<antwort korrekt="false">setsock</antwort>
		<antwort korrekt="false">open</antwort>
	</fragenblock>
	<fragenblock timeout="45">
		<frage>Während eines read-Aufrufs tritt ein Signal auf und wird durch einen Signalhandler abgearbeitet (SA_RESTART nicht gesetzt). Was passiert?
		</frage>
		<antwort korrekt="true">Der Aufruf kehrt unter Umständen mit weniger Daten als angefordert oder EINTR zurück.</antwort>
		<antwort korrekt="false">Es werden auf jeden Fall so viele Daten gelesen wie angefordert.</antwort>
		<antwort korrekt="false">Die Daten gehen verloren.</antwort>
		<antwort korrekt="false">Das Programm wird in solchen Fällen vom Betriebssystem abgebrochen.</antwort>
	</fragenblock>
	<fragenblock timeout="20">
		<frage>Beim Lesen aus einer Pipe meldet der Aufruf read das Dateiende, wenn...
		</frage>
		<antwort korrekt="true">...alle Schreib-Deskriptoren für die Pipe geschlossen und alle Daten aus der Pipe gelesen wurden.</antwort>
		<antwort korrekt="false">...der Leser ein spezielles Signal erhält.</antwort>
		<antwort korrekt="false">...der schreibende Prozess fork aufruft.</antwort>
		<antwort korrekt="false">...^D in die Pipe geschrieben wird.</antwort>
	</fragenblock>
	<fragenblock timeout="30">
		<frage>Was passiert mit einem Shared-Memory-Objekt, wenn es nicht manuell gelöscht wird?
		</frage>
		<antwort korrekt="true">Es bleibt weiterhin bestehen, bis es von Hand oder durch einen Reboot gelöscht wurde.</antwort>
		<antwort korrekt="false">Es wird zerstört, wenn sich der Prozess beendet, der es erzeugt hat.</antwort>
		<antwort korrekt="false">Es wird zerstört, wenn kein Prozess mehr auf es zugreift.</antwort>
		<antwort korrekt="false">Der Garbage-Collector des Betriebssystems zerstört es, wenn der Speicher knapp wird.</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Welches dieser Signale kann nicht abgefangen werden?</frage>
		<antwort korrekt="true">SIGKILL</antwort>
		<antwort korrekt="false">SIGTERM</antwort>
		<antwort korrekt="false">SIGINT</antwort>
		<antwort korrekt="false">SIGPIPE</antwort>
	</fragenblock>
	<fragenblock timeout="30">
		<frage>Was ist ein Zombie-Prozess unter Unix?</frage>
		<antwort korrekt="true">Ein Prozess, dessen Exit-Status noch nicht mittels wait abgefragt wurde.</antwort>
		<antwort korrekt="false">Ein Daemon-Prozess, der durch den Aufruf zombie immun gegen das KILL-Signal gemacht wurde.</antwort>
		<antwort korrekt="false">Ein Prozess, der nur nachts gestartet werden kann.</antwort>
		<antwort korrekt="false">Ein Computervirus.</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Welches Signal (sofern nicht ignoriert) empfängt ein Elternprozess, wenn sich einer seiner Kindprozesse beendet?
		</frage>
		<antwort korrekt="true">SIGCHLD</antwort>
		<antwort korrekt="false">SIGSYS</antwort>
		<antwort korrekt="false">SIGSEGV</antwort>
		<antwort korrekt="false">SIGABRT</antwort>
	</fragenblock>
</fragenkatalog>

=== Werner91/WebProg_v2/catalogs/simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/xmlstyle.xsl"?>
<fragenkatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema_fragenkatalog.xsd" name="simple" fragenanzahl="6">
	<fragenblock>
		<frage>Welcher Mechanismus kann unter Unix zur Kommunikation über das Netzwerk verwendet werden?</frage>
		<antwort korrekt="true">Sockets</antwort>
		<antwort korrekt="false">Message Queues</antwort>
		<antwort korrekt="false">Pipes</antwort>
		<antwort korrekt="false">Semaphore</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Die Hauptstadt von Italien ist:</frage>
		<antwort korrekt="true">Rom</antwort>
		<antwort korrekt="false">Athen</antwort>
		<antwort korrekt="false">Bonn</antwort>
		<antwort korrekt="false">Madrid</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Die Quadratwurzel von 100 ist:</frage>
		<antwort korrekt="true">10</antwort>
		<antwort korrekt="false">2,76</antwort>
		<antwort korrekt="false">5</antwort>
		<antwort korrekt="false">1</antwort>
	</fragenblock>
	<fragenblock>
		<frage>1+1=?</frage>
		<antwort korrekt="true">2</antwort>
		<antwort korrekt="false">11</antwort>
		<antwort korrekt="false">17</antwort>
		<antwort korrekt="false">3</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Spinnen...</frage>
		<antwort korrekt="true">...haben 8 Beine</antwort>
		<antwort korrekt="false">...sind Insekten</antwort>
		<antwort korrekt="false">...sind Vögel</antwort>
		<antwort korrekt="false">...werden bis zu 100 Jahre alt</antwort>
	</fragenblock>
	<fragenblock>
		<frage>Die Hauptstadt von Spanien ist:</frage>
		<antwort korrekt="true">Madrid</antwort>
		<antwort korrekt="false">Barcelona</antwort>
		<antwort korrekt="false">Rom</antwort>
		<antwort korrekt="false">London</antwort>
	</fragenblock>
</fragenkatalog>
